[project]
name = "files-to-sql"
version = "0.1.0"
description = "Importa arquivos XLSX para tabelas SQL com SQLAlchemy"
authors = [
    {name = "GitHub Copilot"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)"
]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
